implementacao da entidade Transaction, e o ITransactionRepository
RuaniFilipe/MM4Bank pull request #2
Opened 2021-11-03 17:33 UTC by rodrigo-militao

2021-11-03 18:08 UTC, julioKauer requested changes
Opa Militão, dá uma olhada se faz sentido meus questionamentos.

2021-11-03 18:08 UTC, julioKauer commented on MM4Bank.Domain/Entities/Transaction.cs
> +        public DateTime DataTransferencia { get; set; } = DateTime.Now;
O entity deveria ter um  createdAt daí esse campo sobraria.

2021-11-03 18:08 UTC, julioKauer commented on MM4Bank.Domain/Entities/Transaction.cs
> +        public double Valor { get; set; }
Não seria melhor usar nomes em inglês para padronizar?

2021-11-03 18:08 UTC, julioKauer commented on MM4Bank.Domain/Entities/Transaction.cs
> +            ValidateDomain(valor, contaOrigem, contaDestino);
Depois de validar a transação o valor deve ser subtraído da conta de origem e somado na conta destino.

2021-11-03 18:08 UTC, julioKauer commented on MM4Bank.Domain/Entities/Transaction.cs
> +            ContaDestino = contaDestino;
Deveria ser feita a validação de se a transação é possível, existe saldo suficiente na conta origem.

2021-11-03 21:35 UTC, rodrigo-militao commented on MM4Bank.Domain/Entities/Transaction.cs
> +            ValidateDomain(valor, contaOrigem, contaDestino);
Isso não seria no método de transferencia ? Pq essa classe é transação, ela pode ser uma transferencia, um saque, ou qlqr coisa .. O q acha ?

2021-11-03 21:36 UTC, rodrigo-militao commented on MM4Bank.Domain/Entities/Transaction.cs
> +        public double Valor { get; set; }
Sim, tem razão, feito!

2021-11-03 21:36 UTC, rodrigo-militao commented on MM4Bank.Domain/Entities/Transaction.cs
> +        public DateTime DataTransferencia { get; set; } = DateTime.Now;
Feito!

2021-11-03 22:01 UTC, RuaniFilipe approved these changes

2021-11-04 00:51 UTC, julioKauer commented on MM4Bank.Domain/Entities/Transaction.cs
> +            ValidateDomain(valor, contaOrigem, contaDestino);
Tá certo, estava confundindo os nomes e também esqueci de guardar as transações no saque e depósito.

2021-11-04 00:52 UTC, julioKauer approved these changes

2021-11-04 00:55 UTC, merged